-- Snowflake tables for streaming VWAP aggregates
-- Run in Snowflake UI (app.snowflake.com) or SnowSQL

USE DATABASE MARKET_DATA_DB;
CREATE SCHEMA IF NOT EXISTS STREAMING_ANALYTICS;

CREATE TABLE IF NOT EXISTS STREAMING_ANALYTICS.VWAP_1MIN (
    WINDOW_START TIMESTAMP_NTZ,
    WINDOW_END TIMESTAMP_NTZ,
    TICKER VARCHAR(10),
    VWAP FLOAT,
    LOW_PRICE FLOAT,
    HIGH_PRICE FLOAT,
    AVG_PRICE FLOAT,
    TOTAL_VOLUME INTEGER,
    TOTAL_DOLLAR_VOLUME FLOAT,
    TRADE_COUNT INTEGER,
    BUY_VOLUME INTEGER,
    SELL_VOLUME INTEGER,
    BUY_PRESSURE FLOAT,
    AVG_SPREAD FLOAT,
    AVG_BID FLOAT,
    AVG_ASK FLOAT,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS STREAMING_ANALYTICS.VWAP_5MIN (
    WINDOW_START TIMESTAMP_NTZ,
    WINDOW_END TIMESTAMP_NTZ,
    TICKER VARCHAR(10),
    VWAP FLOAT,
    LOW_PRICE FLOAT,
    HIGH_PRICE FLOAT,
    AVG_PRICE FLOAT,
    TOTAL_VOLUME INTEGER,
    TOTAL_DOLLAR_VOLUME FLOAT,
    TRADE_COUNT INTEGER,
    BUY_VOLUME INTEGER,
    SELL_VOLUME INTEGER,
    BUY_PRESSURE FLOAT,
    AVG_SPREAD FLOAT,
    AVG_BID FLOAT,
    AVG_ASK FLOAT,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
