# Author: Janvi Chitroda | github.com/JanviChitroda24
"""
One-Command Integration Test

Starts producer + processor, waits for pipeline to populate all sinks,
then validates all 4 Delta tables have rows.

Output (overwrite each run):
  docs/integration_test_report.md

Run:
  cd src
  python integration_test.py

Prerequisite: Redpanda running (docker compose up -d).
Duration: ~75 seconds.
"""

import os
import signal
import subprocess
import sys
import time
from datetime import datetime

from config import (
    DELTA_ANOMALY_ALERTS,
    DELTA_RAW_TRADES,
    DELTA_VWAP_1MIN,
    DELTA_VWAP_5MIN,
    KAFKA_BOOTSTRAP_SERVERS,
)
from spark_config import get_spark_session

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_SRC_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_PATH = os.path.join(_REPO_ROOT, "docs", "integration_test_report.md")

PRODUCER_EPS = 50
PRODUCER_DURATION_SEC = 60
PIPELINE_WAIT_SEC = 75
GRACEFUL_STOP_TIMEOUT_SEC = 30


def _check_kafka() -> None:
    """Fail fast if Redpanda/Kafka is not reachable."""
    try:
        from kafka import KafkaAdminClient

        admin = KafkaAdminClient(
            bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
            request_timeout_ms=5000,
        )
        admin.close()
    except Exception as exc:
        print(f"ERROR: Cannot reach Kafka at {KAFKA_BOOTSTRAP_SERVERS}")
        print("Start Redpanda first: docker compose up -d")
        print(f"Detail: {exc}")
        raise SystemExit(1) from exc


def _stop_process(proc: subprocess.Popen, sig: int = signal.SIGINT, timeout: int = 10) -> None:
    """Send signal and wait; force-kill if the process does not exit."""
    if proc.poll() is not None:
        return
    try:
        proc.send_signal(sig)
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=5)


def run_integration_test() -> bool:
    """Run full pipeline end-to-end and validate all Delta tables."""
    _check_kafka()

    lines: list[str] = []
    lines.append("# Integration Test Report")
    lines.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("\n---\n")

    print("=== INTEGRATION TEST ===\n")

    print(f"Starting producer ({PRODUCER_DURATION_SEC}s, {PRODUCER_EPS} eps)...")
    producer_proc = subprocess.Popen(
        [
            sys.executable,
            "producer.py",
            "--mode",
            "simulated",
            "--eps",
            str(PRODUCER_EPS),
            "--duration",
            str(PRODUCER_DURATION_SEC),
        ],
        cwd=_SRC_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    print("Starting processor...")
    processor_proc = subprocess.Popen(
        [sys.executable, "stream_processor.py"],
        cwd=_SRC_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    print(f"Waiting {PIPELINE_WAIT_SEC} seconds for pipeline to complete...")
    time.sleep(PIPELINE_WAIT_SEC)

    _stop_process(processor_proc, signal.SIGINT, GRACEFUL_STOP_TIMEOUT_SEC)
    _stop_process(producer_proc, signal.SIGINT, 10)

    spark = get_spark_session("IntegrationTest")
    spark.sparkContext.setLogLevel("ERROR")

    tables = [
        ("raw_trades", DELTA_RAW_TRADES),
        ("vwap_1min", DELTA_VWAP_1MIN),
        ("vwap_5min", DELTA_VWAP_5MIN),
        ("anomaly_alerts", DELTA_ANOMALY_ALERTS),
    ]

    results: dict[str, int] = {}
    for name, path in tables:
        try:
            if os.path.exists(path):
                results[name] = spark.read.format("delta").load(path).count()
            else:
                results[name] = 0
        except Exception:
            results[name] = 0

    spark.stop()

    print("\n--- RESULTS ---")
    lines.append("## Results\n")
    lines.append("| Table | Rows | Status |")
    lines.append("|-------|------|--------|")

    all_pass = True
    for name, count in results.items():
        status = "✅ PASS" if count > 0 else "❌ FAIL"
        if count == 0:
            all_pass = False
        print(f"  {status} {name}: {count:,} rows")
        lines.append(f"| {name} | {count:,} | {status} |")

    if all_pass:
        print("\n✅ ALL TABLES POPULATED — integration test PASSED")
        lines.append("\n✅ **ALL TABLES POPULATED — integration test PASSED**")
    else:
        print("\n❌ SOME TABLES EMPTY — integration test FAILED")
        lines.append("\n❌ **SOME TABLES EMPTY — integration test FAILED**")

    lines.append("\n---")
    lines.append(f"\n*Report generated by `integration_test.py` at {datetime.now().isoformat()}*")

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"\nReport saved to: {REPORT_PATH}")
    return all_pass


if __name__ == "__main__":
    success = run_integration_test()
    raise SystemExit(0 if success else 1)
