"""
Show which tickers land on which Kafka partitions.

Demonstrates key-based partitioning: same ticker always goes to the same partition,
guaranteeing ordering per ticker (critical for VWAP accuracy).

Prerequisite: Redpanda running (docker compose up -d).

Output (overwrite each run):
  docs/kafka_partition_map.md

Run:
  cd src
  python show_partitions.py
"""

import os
from datetime import datetime

from kafka import KafkaProducer
from kafka.errors import NoBrokersAvailable

from config import KAFKA_BOOTSTRAP_SERVERS, KAFKA_PARTITIONS, KAFKA_TOPIC, TICKERS

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REPORT_PATH = os.path.join(_REPO_ROOT, "docs", "kafka_partition_map.md")


def show_partitions() -> None:
    """Send one test message per ticker (key=ticker) and record assigned partition."""
    try:
        producer = KafkaProducer(
            bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
            key_serializer=lambda k: k.encode("utf-8"),
        )
    except NoBrokersAvailable:
        print("ERROR: Cannot connect to Kafka. Start Redpanda: docker compose up -d")
        raise SystemExit(1)

    # partition -> list of tickers that hash to this partition
    partitions: dict[int, list[str]] = {}

    for ticker in sorted(TICKERS):
        # key=ticker — same as producer.py; Kafka murmur2 hash picks partition
        future = producer.send(KAFKA_TOPIC, key=ticker, value=b"partition_test")
        record = future.get(timeout=5)
        partitions.setdefault(record.partition, []).append(ticker)

    producer.close()

    # Console output
    print(f"\n{'Partition':<12} {'Count':<8} {'Tickers'}")
    print("-" * 60)
    for partition_id in sorted(partitions):
        tickers = partitions[partition_id]
        print(f"{partition_id:<12} {len(tickers):<8} {', '.join(tickers)}")

    _write_report(partitions)
    print(f"\nReport saved to: {REPORT_PATH}")


def _write_report(partitions: dict[int, list[str]]) -> None:
    lines: list[str] = []
    lines.append("# Kafka Partition Map")
    lines.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(
        f"\n**Topic:** {KAFKA_TOPIC} | **Partitions:** {KAFKA_PARTITIONS} | "
        f"**Tickers:** {len(TICKERS)}"
    )
    lines.append("\n---\n")

    lines.append("## Partition Assignment\n")
    lines.append("| Partition | Ticker Count | Tickers |")
    lines.append("|-----------|-------------|---------|")
    for partition_id in sorted(partitions):
        tickers = partitions[partition_id]
        lines.append(f"| {partition_id} | {len(tickers)} | {', '.join(tickers)} |")

    lines.append("\n## How It Works\n")
    lines.append(
        "Messages are keyed by ticker symbol. Kafka's default murmur2 partitioner computes:"
    )
    lines.append("\n```")
    lines.append("partition = hash(ticker_bytes) % num_partitions")
    lines.append("```\n")
    lines.append(
        "Same ticker always maps to the same partition, guaranteeing ordering per ticker."
    )

    lines.append("\n## Why This Matters\n")
    lines.append(
        "1. **Ordering guarantee** — All AAPL trades arrive in order within their partition. "
        "Critical for VWAP: trade A at $210.00 must be processed before trade B at $210.05."
    )
    lines.append(
        "2. **Parallelism** — Spark reads each partition with a separate task. "
        f"{KAFKA_PARTITIONS} partitions = up to {KAFKA_PARTITIONS}x throughput."
    )
    lines.append(
        "3. **Even distribution** — 25 tickers across 3 partitions gives roughly 8–9 tickers "
        "per partition. No hot partition."
    )
    lines.append(
        "4. **Consumer groups** — Multiple consumers (streaming + batch reconciliation) can "
        "read independently without interference."
    )

    lines.append("\n## Distribution Quality\n")
    counts = [len(v) for v in partitions.values()]
    max_c, min_c = max(counts), min(counts)
    skew = max_c - min_c
    lines.append(f"- Max tickers in one partition: {max_c}")
    lines.append(f"- Min tickers in one partition: {min_c}")
    lines.append(f"- Skew (max - min): {skew}")
    if skew <= 2:
        lines.append(f"\n✅ **Well balanced** — skew of {skew} is excellent for 3 partitions.")
    else:
        lines.append("\n⚠️ **Slightly skewed** — consider increasing partition count.")

    lines.append("\n---")
    lines.append(f"\n*Report generated by `show_partitions.py` at {datetime.now().isoformat()}*")

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    show_partitions()
